return {
  { 'Alligator/accent.vim' },
  { 'LuRsT/austere.vim' },
  { 'aditya-azad/candle-grey' },
  { 'fxn/vim-monochrome' },
  { 'rose-pine/neovim' },
  { 'huyvohcmc/atlas.vim' },
  { 'owickstrom/vim-colors-paramount' },
  { 'ribru17/bamboo.nvim' },
  { 'catppuccin/nvim', name = 'catppuccin' },
  { 'dgox16/oldworld.nvim' },
  { 'rebelot/kanagawa.nvim' },
  { 'AlexvZyl/nordic.nvim' },
  { 'cdmill/neomodern.nvim' },
}
