return {
  { 'projekt0n/github-nvim-theme', name = 'github-theme' },
  { 'ellisonleao/gruvbox.nvim' },
  { 'ficcdaf/ashen.nvim' },
  { 'pustota-theme/pustota.nvim' },
  { 'nyoom-engineering/oxocarbon.nvim' },
  { 'miikanissi/modus-themes.nvim' },
  { 'rose-pine/neovim' },
  { 'EdenEast/nightfox.nvim' },
  { 'mhartington/oceanic-next' },
  { 'rebelot/kanagawa.nvim' },
  { 'sainnhe/gruvbox-material' },
  { 'Tsuzat/NeoSolarized.nvim' },
  { 'folke/tokyonight.nvim' },
  {
    'catppuccin/nvim',
    name = 'catppuccin',
    event = 'VimEnter',
  },
  {
    'craftzdog/solarized-osaka.nvim',
    lazy = false,
    priority = 1000,
    opts = {
      transparent = true,
    },
  },
  { 'scottmckendry/cyberdream.nvim' },
  { 'navarasu/onedark.nvim' },
  { 'Shatur/neovim-ayu' },
  { 'ramojus/mellifluous.nvim' },
  { 'cpwrs/americano.nvim' },
  { 'embark-theme/vim' },
  {
    'zenbones-theme/zenbones.nvim',
    dependencies = 'rktjmp/lush.nvim',
    lazy = false,
    priority = 1000,
  },
  { 'ricardoraposo/nightwolf.nvim' },
  { 'WTFox/jellybeans.nvim' },

  -- monochrome

  { 'andreasvc/vim-256noir' },
  -- { 'chriskempson/base16-vim' },
  { 'ntk148v/komau.vim' },
  { 'andreypopp/vim-colors-plain' },
  { 'karoliskoncevicius/distilled-vim' },
  { 'jaredgorski/Mies.vim' },
}
