# Check Lua Formatting
name: Check Lua Formatting
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  stylua-check:
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Stylua Check
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          version: latest
          args: --check .
